#!/usr/bin/env bun
/**
 * Deploy vozcoletiva to AWS.
 *
 *   bun run deploy --env dev               # local dev deploy
 *   bun run deploy --env prod              # refuses unless GITHUB_ACTIONS=true
 *   bun run deploy --env dev --dry-run     # cdk diff only
 *
 * Guards:
 *   1. --env arg required, dev or prod.
 *   2. Working tree must be on `main`.
 *   3. Working tree must be clean.
 *   4. --env prod refuses outside GitHub Actions (override with VOZ_FORCE_PROD_DEPLOY=1).
 *
 * Pipeline:
 *   1. Build the Rust Lambda via cargo-lambda (arm64, release).
 *   2. Build the web app via `bun --filter @vozcoletiva/web run build`.
 *   3. `cdk deploy` (BucketDeployment uploads the web dist + invalidates CloudFront).
 */

import { execSync, spawnSync } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

interface StackOutputs {
  apiUrl: string;
  userPoolId: string;
  userPoolClientId: string;
  region: string;
}

function readStackOutputs(env: 'dev' | 'prod'): StackOutputs | null {
  const region = env === 'dev' || env === 'prod' ? 'eu-west-1' : 'eu-west-1';
  const stackName = `voz-${env}`;
  const r = spawnSync(
    'aws',
    [
      'cloudformation',
      'describe-stacks',
      '--stack-name',
      stackName,
      '--region',
      region,
      '--query',
      'Stacks[0].Outputs',
      '--output',
      'json',
    ],
    { encoding: 'utf8' },
  );
  if (r.status !== 0) {
    return null; // stack doesn't exist yet
  }
  const outputs = JSON.parse(r.stdout) as Array<{ OutputKey: string; OutputValue: string }>;
  const byKey = Object.fromEntries(outputs.map((o) => [o.OutputKey, o.OutputValue]));
  const apiUrl = byKey['ApiUrl'];
  const userPoolId = byKey['UserPoolId'];
  const userPoolClientId = byKey['UserPoolClientId'];
  if (!apiUrl || !userPoolId || !userPoolClientId) {
    return null;
  }
  // Trim trailing slash so the FE can build paths like `${base}/v1/me` cleanly.
  return {
    apiUrl: apiUrl.replace(/\/$/, ''),
    userPoolId,
    userPoolClientId,
    region,
  };
}

function writeWebEnvFile(env: 'dev' | 'prod', outputs: StackOutputs, root: string) {
  const path = resolve(root, 'apps/web/.env.production');
  const lines = [
    `# Generated by apps/infra/scripts/deploy.ts during 'deploy --env ${env}'`,
    `# Do not edit by hand — re-run the deploy script.`,
    `VITE_API_BASE_URL=${outputs.apiUrl}`,
    `VITE_USER_POOL_ID=${outputs.userPoolId}`,
    `VITE_USER_POOL_CLIENT_ID=${outputs.userPoolClientId}`,
    `VITE_AWS_REGION=${outputs.region}`,
    // Pin mocks off — `.env.local` (a dev convenience) sets VITE_USE_MOCKS=1 and
    // Vite loads it in production builds too; `.env.production` (this file) is the
    // higher-precedence mode file, so it must override or the build ships full
    // mocks instead of the real API.
    'VITE_USE_MOCKS=0',
    // Dev only: messages / DMs / inbox / search have no backend yet, so MSW
    // serves mock data for just those endpoints (real API for everything else).
    // Never set for prod — the prod-mock guard would reject it anyway.
    ...(env === 'dev' ? ['VITE_MOCK_COMMS=1'] : []),
    '',
  ];
  writeFileSync(path, lines.join('\n'), 'utf8');
  console.log(`  wrote ${path}`);
}

interface Args {
  env: 'dev' | 'prod';
  dryRun: boolean;
}

function parseArgs(): Args {
  const argv = process.argv.slice(2);
  let env: string | undefined;
  let dryRun = false;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--env') {
      env = argv[++i];
    } else if (a?.startsWith('--env=')) {
      env = a.split('=')[1];
    } else if (a === '--dry-run') {
      dryRun = true;
    }
  }
  if (env !== 'dev' && env !== 'prod') {
    die('usage: deploy --env <dev|prod> [--dry-run]');
  }
  return { env, dryRun };
}

function die(msg: string): never {
  console.error(`✗ ${msg}`);
  process.exit(1);
}

function run(cmd: string, opts: { cwd?: string; env?: NodeJS.ProcessEnv } = {}) {
  console.log(`\n$ ${cmd}`);
  const r = spawnSync(cmd, {
    cwd: opts.cwd,
    env: { ...process.env, ...opts.env },
    stdio: 'inherit',
    shell: true,
  });
  if (r.status !== 0) {
    die(`command failed (exit ${r.status}): ${cmd}`);
  }
}

function checkBranch() {
  const branch = execSync('git rev-parse --abbrev-ref HEAD').toString().trim();
  if (branch !== 'main') {
    die(`must deploy from 'main' (currently on '${branch}')`);
  }
}

function checkCleanTree() {
  const status = execSync('git status --porcelain').toString().trim();
  if (status) {
    die(`working tree not clean:\n${status}`);
  }
}

function checkProdGuard(env: 'dev' | 'prod') {
  if (env !== 'prod') return;
  const inGhActions = process.env.GITHUB_ACTIONS === 'true';
  const breakGlass = process.env.VOZ_FORCE_PROD_DEPLOY === '1';
  if (inGhActions) return;
  if (breakGlass) {
    console.warn('\n⚠ BREAK-GLASS PROD DEPLOY: deploying prod from a developer machine.');
    console.warn('   Log this to the audit trail and announce in writing.');
    return;
  }
  die(
    "refusing to deploy '--env prod' from a developer machine.\n" +
      "  Prod deploys land via the GitHub Actions workflow on push to 'main'.\n" +
      '  Break-glass: set VOZ_FORCE_PROD_DEPLOY=1 (and log it).',
  );
}

async function main() {
  const args = parseArgs();
  const root = resolve(HERE, '..', '..', '..');

  if (!args.dryRun) {
    checkBranch();
    checkCleanTree();
  }
  checkProdGuard(args.env);

  console.log(`\n=== vozcoletiva deploy → ${args.env}${args.dryRun ? ' (dry-run)' : ''} ===`);

  // 1. Build Rust Lambda. cargo-lambda is smart about incremental compilation;
  // always invoking it is fine and avoids stale-artifact pitfalls.
  console.log('\n• building Rust Lambda (cargo lambda build --release --arm64)…');
  const probe = spawnSync('cargo lambda --version', { shell: true });
  if (probe.status !== 0) {
    console.error(
      '\n✗ cargo-lambda is not installed. Install it once:\n' +
        '    cargo install cargo-lambda\n' +
        '  Then re-run this command.',
    );
    process.exit(1);
  }
  run('cargo lambda build --release --arm64 -p voz-api', { cwd: root });
  if (!existsSync(resolve(root, 'target/lambda/voz-api/bootstrap'))) {
    die('Lambda build did not produce target/lambda/voz-api/bootstrap');
  }

  // 2. Read CDK outputs and inject into the web build env.
  console.log('\n• reading stack outputs for env injection…');
  const outputs = readStackOutputs(args.env);
  if (!outputs) {
    console.log(
      `  no existing outputs for voz-${args.env} (first deploy?). Building web with the developer's local .env.local.`,
    );
  } else {
    writeWebEnvFile(args.env, outputs, root);
  }

  // 3. Build web app — but first guard against shipping mocks.
  if (args.env === 'prod' && process.env.VITE_USE_MOCKS && process.env.VITE_USE_MOCKS !== '0') {
    die(
      'refusing to deploy --env prod with VITE_USE_MOCKS set.\n' +
        '  The mock layer must not ship to production. Unset the var and re-run.',
    );
  }
  console.log('\n• building web app…');
  run('bun run build', {
    cwd: resolve(root, 'apps/web'),
    // Dev ships the comms-hybrid: VITE_MOCK_COMMS must be in the *process* env
    // so vite.config (Node) sees it for `selfDestroying`, and in the client
    // bundle so `main.tsx` starts the comms mocks. Prod ships no mocks.
    env: args.env === 'prod' ? { VITE_USE_MOCKS: '0' } : { VITE_MOCK_COMMS: '1' },
  });
  // Belt-and-braces: scan the prod bundle for any MSW residue.
  if (args.env === 'prod') {
    const distDir = resolve(root, 'apps/web/dist');
    if (existsSync(distDir)) {
      const grep = spawnSync(`grep -rEl '(mockServiceWorker|setupWorker|msw/browser)' "${distDir}" || true`, {
        shell: true,
        encoding: 'utf8',
      });
      const offenders = (grep.stdout || '').split('\n').filter(Boolean);
      if (offenders.length > 0) {
        die(
          `prod build contains MSW residue — refusing to deploy.\n  Offending files:\n    ${offenders.join('\n    ')}`,
        );
      }
    }
  }

  // 4. CDK deploy (or diff).
  const cdkEnv = { VOZ_ENV: args.env };
  if (args.dryRun) {
    run(`bunx cdk diff '${stackName(args.env)}'`, {
      cwd: resolve(root, 'apps/infra'),
      env: cdkEnv,
    });
  } else {
    run(`bunx cdk deploy '${stackName(args.env)}' --require-approval never`, {
      cwd: resolve(root, 'apps/infra'),
      env: cdkEnv,
    });
  }

  console.log('\n✓ deploy complete');
}

function stackName(env: 'dev' | 'prod'): string {
  return `voz-${env}`;
}

await main();
