/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as JoinRouteImport } from './routes/join'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as DmsRouteImport } from './routes/dms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpVerifyRouteImport } from './routes/sign-up_.verify'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ITokenRouteImport } from './routes/i_.$token'
import { Route as DmsIdRouteImport } from './routes/dms_.$id'
import { Route as PSlugIndexRouteImport } from './routes/p.$slug.index'
import { Route as PSlugSearchRouteImport } from './routes/p.$slug.search'
import { Route as PSlugMessagesRouteImport } from './routes/p.$slug.messages'
import { Route as PSlugMembersRouteImport } from './routes/p.$slug.members'
import { Route as PSlugManageRouteImport } from './routes/p.$slug.manage'
import { Route as PSlugInvitesRouteImport } from './routes/p.$slug.invites'
import { Route as PSlugDocumentsRouteImport } from './routes/p.$slug.documents'
import { Route as PSlugCategoriesRouteImport } from './routes/p.$slug.categories'
import { Route as PSlugProposalsNewRouteImport } from './routes/p.$slug.proposals.new'
import { Route as PSlugProposalsIdRouteImport } from './routes/p.$slug.proposals.$id'
import { Route as PSlugMessagesChannelIdRouteImport } from './routes/p.$slug.messages_.$channelId'
import { Route as PSlugDocumentsNameRouteImport } from './routes/p.$slug.documents_.$name'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DmsRoute = DmsRouteImport.update({
  id: '/dms',
  path: '/dms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpVerifyRoute = SignUpVerifyRouteImport.update({
  id: '/sign-up_/verify',
  path: '/sign-up/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ITokenRoute = ITokenRouteImport.update({
  id: '/i_/$token',
  path: '/i/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DmsIdRoute = DmsIdRouteImport.update({
  id: '/dms_/$id',
  path: '/dms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugIndexRoute = PSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugSearchRoute = PSlugSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugMessagesRoute = PSlugMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugMembersRoute = PSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugManageRoute = PSlugManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugInvitesRoute = PSlugInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugDocumentsRoute = PSlugDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugCategoriesRoute = PSlugCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugProposalsNewRoute = PSlugProposalsNewRouteImport.update({
  id: '/proposals/new',
  path: '/proposals/new',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugProposalsIdRoute = PSlugProposalsIdRouteImport.update({
  id: '/proposals/$id',
  path: '/proposals/$id',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugMessagesChannelIdRoute = PSlugMessagesChannelIdRouteImport.update({
  id: '/messages_/$channelId',
  path: '/messages/$channelId',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugDocumentsNameRoute = PSlugDocumentsNameRouteImport.update({
  id: '/documents_/$name',
  path: '/documents/$name',
  getParentRoute: () => PSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dms': typeof DmsRoute
  '/inbox': typeof InboxRoute
  '/join': typeof JoinRoute
  '/preferences': typeof PreferencesRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/sign-up': typeof SignUpRoute
  '/welcome': typeof WelcomeRoute
  '/dms/$id': typeof DmsIdRoute
  '/i/$token': typeof ITokenRoute
  '/p/$slug': typeof PSlugRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/sign-up/verify': typeof SignUpVerifyRoute
  '/p/$slug/categories': typeof PSlugCategoriesRoute
  '/p/$slug/documents': typeof PSlugDocumentsRoute
  '/p/$slug/invites': typeof PSlugInvitesRoute
  '/p/$slug/manage': typeof PSlugManageRoute
  '/p/$slug/members': typeof PSlugMembersRoute
  '/p/$slug/messages': typeof PSlugMessagesRoute
  '/p/$slug/search': typeof PSlugSearchRoute
  '/p/$slug/': typeof PSlugIndexRoute
  '/p/$slug/documents/$name': typeof PSlugDocumentsNameRoute
  '/p/$slug/messages/$channelId': typeof PSlugMessagesChannelIdRoute
  '/p/$slug/proposals/$id': typeof PSlugProposalsIdRoute
  '/p/$slug/proposals/new': typeof PSlugProposalsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dms': typeof DmsRoute
  '/inbox': typeof InboxRoute
  '/join': typeof JoinRoute
  '/preferences': typeof PreferencesRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/sign-up': typeof SignUpRoute
  '/welcome': typeof WelcomeRoute
  '/dms/$id': typeof DmsIdRoute
  '/i/$token': typeof ITokenRoute
  '/projects/new': typeof ProjectsNewRoute
  '/sign-up/verify': typeof SignUpVerifyRoute
  '/p/$slug/categories': typeof PSlugCategoriesRoute
  '/p/$slug/documents': typeof PSlugDocumentsRoute
  '/p/$slug/invites': typeof PSlugInvitesRoute
  '/p/$slug/manage': typeof PSlugManageRoute
  '/p/$slug/members': typeof PSlugMembersRoute
  '/p/$slug/messages': typeof PSlugMessagesRoute
  '/p/$slug/search': typeof PSlugSearchRoute
  '/p/$slug': typeof PSlugIndexRoute
  '/p/$slug/documents/$name': typeof PSlugDocumentsNameRoute
  '/p/$slug/messages/$channelId': typeof PSlugMessagesChannelIdRoute
  '/p/$slug/proposals/$id': typeof PSlugProposalsIdRoute
  '/p/$slug/proposals/new': typeof PSlugProposalsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dms': typeof DmsRoute
  '/inbox': typeof InboxRoute
  '/join': typeof JoinRoute
  '/preferences': typeof PreferencesRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/sign-up': typeof SignUpRoute
  '/welcome': typeof WelcomeRoute
  '/dms_/$id': typeof DmsIdRoute
  '/i_/$token': typeof ITokenRoute
  '/p/$slug': typeof PSlugRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/sign-up_/verify': typeof SignUpVerifyRoute
  '/p/$slug/categories': typeof PSlugCategoriesRoute
  '/p/$slug/documents': typeof PSlugDocumentsRoute
  '/p/$slug/invites': typeof PSlugInvitesRoute
  '/p/$slug/manage': typeof PSlugManageRoute
  '/p/$slug/members': typeof PSlugMembersRoute
  '/p/$slug/messages': typeof PSlugMessagesRoute
  '/p/$slug/search': typeof PSlugSearchRoute
  '/p/$slug/': typeof PSlugIndexRoute
  '/p/$slug/documents_/$name': typeof PSlugDocumentsNameRoute
  '/p/$slug/messages_/$channelId': typeof PSlugMessagesChannelIdRoute
  '/p/$slug/proposals/$id': typeof PSlugProposalsIdRoute
  '/p/$slug/proposals/new': typeof PSlugProposalsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dms'
    | '/inbox'
    | '/join'
    | '/preferences'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/welcome'
    | '/dms/$id'
    | '/i/$token'
    | '/p/$slug'
    | '/projects/new'
    | '/sign-up/verify'
    | '/p/$slug/categories'
    | '/p/$slug/documents'
    | '/p/$slug/invites'
    | '/p/$slug/manage'
    | '/p/$slug/members'
    | '/p/$slug/messages'
    | '/p/$slug/search'
    | '/p/$slug/'
    | '/p/$slug/documents/$name'
    | '/p/$slug/messages/$channelId'
    | '/p/$slug/proposals/$id'
    | '/p/$slug/proposals/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dms'
    | '/inbox'
    | '/join'
    | '/preferences'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/welcome'
    | '/dms/$id'
    | '/i/$token'
    | '/projects/new'
    | '/sign-up/verify'
    | '/p/$slug/categories'
    | '/p/$slug/documents'
    | '/p/$slug/invites'
    | '/p/$slug/manage'
    | '/p/$slug/members'
    | '/p/$slug/messages'
    | '/p/$slug/search'
    | '/p/$slug'
    | '/p/$slug/documents/$name'
    | '/p/$slug/messages/$channelId'
    | '/p/$slug/proposals/$id'
    | '/p/$slug/proposals/new'
  id:
    | '__root__'
    | '/'
    | '/dms'
    | '/inbox'
    | '/join'
    | '/preferences'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/welcome'
    | '/dms_/$id'
    | '/i_/$token'
    | '/p/$slug'
    | '/projects/new'
    | '/sign-up_/verify'
    | '/p/$slug/categories'
    | '/p/$slug/documents'
    | '/p/$slug/invites'
    | '/p/$slug/manage'
    | '/p/$slug/members'
    | '/p/$slug/messages'
    | '/p/$slug/search'
    | '/p/$slug/'
    | '/p/$slug/documents_/$name'
    | '/p/$slug/messages_/$channelId'
    | '/p/$slug/proposals/$id'
    | '/p/$slug/proposals/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DmsRoute: typeof DmsRoute
  InboxRoute: typeof InboxRoute
  JoinRoute: typeof JoinRoute
  PreferencesRoute: typeof PreferencesRoute
  SignInRoute: typeof SignInRoute
  SignOutRoute: typeof SignOutRoute
  SignUpRoute: typeof SignUpRoute
  WelcomeRoute: typeof WelcomeRoute
  DmsIdRoute: typeof DmsIdRoute
  ITokenRoute: typeof ITokenRoute
  PSlugRoute: typeof PSlugRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  SignUpVerifyRoute: typeof SignUpVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dms': {
      id: '/dms'
      path: '/dms'
      fullPath: '/dms'
      preLoaderRoute: typeof DmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up_/verify': {
      id: '/sign-up_/verify'
      path: '/sign-up/verify'
      fullPath: '/sign-up/verify'
      preLoaderRoute: typeof SignUpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i_/$token': {
      id: '/i_/$token'
      path: '/i/$token'
      fullPath: '/i/$token'
      preLoaderRoute: typeof ITokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dms_/$id': {
      id: '/dms_/$id'
      path: '/dms/$id'
      fullPath: '/dms/$id'
      preLoaderRoute: typeof DmsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug/': {
      id: '/p/$slug/'
      path: '/'
      fullPath: '/p/$slug/'
      preLoaderRoute: typeof PSlugIndexRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/search': {
      id: '/p/$slug/search'
      path: '/search'
      fullPath: '/p/$slug/search'
      preLoaderRoute: typeof PSlugSearchRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/messages': {
      id: '/p/$slug/messages'
      path: '/messages'
      fullPath: '/p/$slug/messages'
      preLoaderRoute: typeof PSlugMessagesRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/members': {
      id: '/p/$slug/members'
      path: '/members'
      fullPath: '/p/$slug/members'
      preLoaderRoute: typeof PSlugMembersRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/manage': {
      id: '/p/$slug/manage'
      path: '/manage'
      fullPath: '/p/$slug/manage'
      preLoaderRoute: typeof PSlugManageRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/invites': {
      id: '/p/$slug/invites'
      path: '/invites'
      fullPath: '/p/$slug/invites'
      preLoaderRoute: typeof PSlugInvitesRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/documents': {
      id: '/p/$slug/documents'
      path: '/documents'
      fullPath: '/p/$slug/documents'
      preLoaderRoute: typeof PSlugDocumentsRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/categories': {
      id: '/p/$slug/categories'
      path: '/categories'
      fullPath: '/p/$slug/categories'
      preLoaderRoute: typeof PSlugCategoriesRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/proposals/new': {
      id: '/p/$slug/proposals/new'
      path: '/proposals/new'
      fullPath: '/p/$slug/proposals/new'
      preLoaderRoute: typeof PSlugProposalsNewRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/proposals/$id': {
      id: '/p/$slug/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/p/$slug/proposals/$id'
      preLoaderRoute: typeof PSlugProposalsIdRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/messages_/$channelId': {
      id: '/p/$slug/messages_/$channelId'
      path: '/messages/$channelId'
      fullPath: '/p/$slug/messages/$channelId'
      preLoaderRoute: typeof PSlugMessagesChannelIdRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/documents_/$name': {
      id: '/p/$slug/documents_/$name'
      path: '/documents/$name'
      fullPath: '/p/$slug/documents/$name'
      preLoaderRoute: typeof PSlugDocumentsNameRouteImport
      parentRoute: typeof PSlugRoute
    }
  }
}

interface PSlugRouteChildren {
  PSlugCategoriesRoute: typeof PSlugCategoriesRoute
  PSlugDocumentsRoute: typeof PSlugDocumentsRoute
  PSlugInvitesRoute: typeof PSlugInvitesRoute
  PSlugManageRoute: typeof PSlugManageRoute
  PSlugMembersRoute: typeof PSlugMembersRoute
  PSlugMessagesRoute: typeof PSlugMessagesRoute
  PSlugSearchRoute: typeof PSlugSearchRoute
  PSlugIndexRoute: typeof PSlugIndexRoute
  PSlugDocumentsNameRoute: typeof PSlugDocumentsNameRoute
  PSlugMessagesChannelIdRoute: typeof PSlugMessagesChannelIdRoute
  PSlugProposalsIdRoute: typeof PSlugProposalsIdRoute
  PSlugProposalsNewRoute: typeof PSlugProposalsNewRoute
}

const PSlugRouteChildren: PSlugRouteChildren = {
  PSlugCategoriesRoute: PSlugCategoriesRoute,
  PSlugDocumentsRoute: PSlugDocumentsRoute,
  PSlugInvitesRoute: PSlugInvitesRoute,
  PSlugManageRoute: PSlugManageRoute,
  PSlugMembersRoute: PSlugMembersRoute,
  PSlugMessagesRoute: PSlugMessagesRoute,
  PSlugSearchRoute: PSlugSearchRoute,
  PSlugIndexRoute: PSlugIndexRoute,
  PSlugDocumentsNameRoute: PSlugDocumentsNameRoute,
  PSlugMessagesChannelIdRoute: PSlugMessagesChannelIdRoute,
  PSlugProposalsIdRoute: PSlugProposalsIdRoute,
  PSlugProposalsNewRoute: PSlugProposalsNewRoute,
}

const PSlugRouteWithChildren = PSlugRoute._addFileChildren(PSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DmsRoute: DmsRoute,
  InboxRoute: InboxRoute,
  JoinRoute: JoinRoute,
  PreferencesRoute: PreferencesRoute,
  SignInRoute: SignInRoute,
  SignOutRoute: SignOutRoute,
  SignUpRoute: SignUpRoute,
  WelcomeRoute: WelcomeRoute,
  DmsIdRoute: DmsIdRoute,
  ITokenRoute: ITokenRoute,
  PSlugRoute: PSlugRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  SignUpVerifyRoute: SignUpVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
